### ISSUE TITLE
Exe file missing, fail to startup

### ISSUE THREAD

**Issue by ullp0int3r** [nunnito/nunnix-manga#1]
Hello, I just downloaded this app to take a try. Downloaded it to my Downloads folder as my preferred location, unzipped to the same folder, and click .bat file. Then it happened I got an error dialog said the executable file was not found. By took a look at the correct path and the folder which is (user/../Downloads/Nunnix-Manga/), it looks like the file is not found in that folder. Here is a screenshot of error dialog
![errorDialog](https://user-images.githubusercontent.com/44376988/167961874-0e417c6f-8098-4e2d-ba66-0fefc7275ab0.png)

Computer OS: Windows 10

**Comment by Nunnito** [comment]
Hello!
Maybe your antivirus has deleted the executable when unzipping it? Try to see if the files exist in the zip, if so, it's probably a false positive caused by PyInstaller, see pyinstaller/pyinstaller#5932

**Comment by ullp0int3r** [comment]
After reviewed that original issues, I then decided to try the Virus/Threat System disable as it is still yet to resolve and took a test run. It works pretty well. 

Note: I re-activated it back when the app done successfully run and exited.

**Comment by Nunnito** [comment]
The issue should been fixed with [v0.1.1](https://github.com/nunnito/nunnix-manga/releases/tag/v0.1.1).
No more false positives, I guess
